version: '3'

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    mem_limit: 350m
    ports:
    - 2181
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
  
    
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    mem_limit: 350m
    ports:
    - 9092
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
    - zookeeper
