version: '3'

services:


  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              kafka-producer:
                url: "http://kafka-producer:8080"
              kafka-consumer:
                url: "http://kafka-consumer:8080"
    ports:
      - 8081:8080
    links:
      - kafka
      - kafka-producer
      - kafka-consumer


  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
    - 2181:2181
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
  
    
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
    - 9092:9092
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
    - zookeeper
    
    
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
    - 27017:27017
    volumes:
    - /mongodb/data:/data/db
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10
      
      
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9003:9000
      - 8001:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /portainer/portainer_data:/data

     
  kafka-producer: 
    build: ./kafka-project
    container_name: kafka-producer
    ports:
    - 9000:8080
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - kafka

    
  kafka-consumer: 
    build: ./kafka-consumer
    container_name: kafka-consumer
    ports:
    - 9001:8080
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - kafka
    - mongodb
    
