server:
  port: 9001
spring:
  kafka:
    client-id: kafka-application-2
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: kafka-consumer-group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#    properties:
#      spring.json.trusted.packages: '*'
#      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#      spring.deserializer.value.delegate.class: com.spring.kafkaconsumer.serialization.UserDeserializer
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-data
custom:
  kafka:
    topic:
      users: users
---
